// This file is automatically generated by parse-properties.ts - do not edit manually cause it will be overwritten on next build
// Environment dev configuration for Angular application
export const environment = {
  production: false,
  api: {
    serverUrl: 'http://localhost:8080/api',
  },
};
